site_name: hikari-persist
site_url: https://hikari-persist.wildevstudios.net
copyright: Copyright &copy; 2026 WilDev Studios. This software is protected by copyright and licensed under the MIT license.

repo_url: https://github.com/WilDev-Studios/hikari-persist

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: pink
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - redirects
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3.10/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
          paths: ["."]
          options:
            heading_level: 3
            annotations_path: source
            docstring_style: numpy
            docstring_section_style: spacy
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            extra:
              show_toc: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WilDev-Studios/hikari-persist
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hikari

nav:
  - Home: index.md
  - API Reference:
    - Index: pages/api/index.md
    - hikaripersist.backend:
      - ~.base: pages/api/backend/base.md
      - ~.sqlite: pages/api/backend/sqlite.md
    - hikaripersist.cache: pages/api/cache.md
    - hikaripersist.cached:
      - ~.base: pages/api/cached/base.md
      - ~.channel: pages/api/cached/channel.md
      - ~.guild: pages/api/cached/guild.md
      - ~.member: pages/api/cached/member.md
      - ~.message: pages/api/cached/message.md
      - ~.role: pages/api/cached/role.md
    - hikaripersist.impl:
      - ~.iterator: pages/api/impl/iterator.md
      - ~.query: pages/api/impl/query.md
    - hikaripersist.rule: pages/api/rule.md
  - Changelog:
    - Index: pages/changelog/index.md
    - 0.1.0a3: pages/changelog/0.1.0a3.md
    - 0.1.0a2: pages/changelog/0.1.0a2.md
    - 0.1.0a1: pages/changelog/0.1.0a1.md
  - Lifecycle: pages/lifecycle.md